# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://zephyrtransport.github.io/zephyr-directory
baseurl: /zephyr-directory
zephyr-url: http://zephyrtransport.org
title: Open Code Directory for Transportation Analysis
short-title: Open Code Directory

email: info@zephyrtransport.org
author: Elizabeth Sall
description: The Zephyr Foundation’s mission is to advance rigorous transportation and land use decision-making for the public good by advocating for and supporting improved travel analysis and facilitating its implementation.
copyright: 'Copyright &copy; 2016 Zephyr Foundation. All Rights Reserved.'
credits: 'Site created by Elizabeth Sall, UrbanLabs LLC'

collections:
    articles:
        output: true
    events:
        output: false
    project-groups:
        output: true
    projects:
        output: true



# ----------------------- #
#   Look Settings         #
# ----------------------- #

top-bg-img:
bottom-bh-img:
highlight-color: 0daee1       #turquoise blue
dark-gray-color: 4e4f58       #dark gray
background-highlight: fafafa    #light gray - blueish
highlight-text: f8f8f8          #light gray
default-tile-img: pic07.jpg


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   Social                #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/zephyrtransport
  - title: github
    url: https://github.com/zephyrtransport
  - title: email
    url: http://eepurl.com/ccQL7z
